### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by miketamis** [fisch0920/snapchat#11]
I get the following error

{ message: 'Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)',
  status: -103,
  logged: false }

TypeError: Cannot read property 'feature_settings' of undefined
    at new Session (/Users/miketamis/Desktop/node_modules/snapchat/models/session.js:28:33)
    at /Users/miketamis/Desktop/node_modules/snapchat/index.js:409:24
    at Request.wrapcb [as _callback] (/Users/miketamis/Desktop/node_modules/snapchat/lib/request.js:189:14)
    at Request.self.callback (/Users/miketamis/Desktop/node_modules/snapchat/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/miketamis/Desktop/node_modules/snapchat/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/miketamis/Desktop/node_modules/snapchat/node_modules/request/request.js:1019:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

I added console.log(params); to Session.js to get more info for ticket.

**Comment by Autarc** [comment]
Its the same issue mentioned in #10 . Currently Liam is working on a [solution](https://www.facebook.com/casper4snapchat/posts/1613951015537820) to retrieve the credentials. Will be available soon and as its handled at his service probably not require a change in the code.
